### ISSUE TITLE
[1.8.9] Game crashes and world unloadable after trying to make a Fancy Fluids Strorage tank with chisel blocks

### ISSUE THREAD

**Issue by MattDahEpic** [Lordmau5/FFS-v1.X#30]
**FancyFluidStorage Version:**
1.8.9-1.4.5.69
**MinecraftForge Version:**
Recomended 1.8.9, 1722
**SSP or SMP? (Client or Server):**
SMP, tested in SSP
**Crash Report (via. Pastebin):**
https://paste.ee/p/PzOQG
**What happens / happened?:**
Building a tank with chisel blocks as any of the outer or inner wall blocks crashes the game and the world becomes unloadable with the same crash until the mod is removed. A dedicated server will crash on startup until the mod is removed or the forge 'remove erroring tile entities" config option is enabled.
**How can we reproduce it?:**
https://dl.dropboxusercontent.com/u/146233520/ShareX/2016/01/2016-01-28_10-49-48.mp4

**Comment by Drullkus** [comment]
I'm told Chisel stuff isn't supported at this moment :(

**Comment by MattDahEpic** [comment]
Even if it is not supported, the crashing and unloadability is a bug. Simply don't allow the tank to form if you know it won't work.

**Comment by Selim042** [comment]
Agreed.  Unplayable words I consider major enough bug to figure something out to fix it whether the mod is supported or not.

**Comment by Lordmau5** [comment]
You could've at least read the description on the 1.4.5 **alpha**.

There is a bug that is causing the game to crash on world-load, and I've already taken care of it.
So don't worry.
It just took longer because, as I've mentioned in another Issue, I wasn't at home from Thursday to Sunday.
Also, the bloody fake-renderer was a pain in the arse to do.

**Comment by Lordmau5** [comment]
Fixed in 1.4.5!
