### ISSUE TITLE
Server crash on load, but really odd instance

### ISSUE THREAD

**Issue by BrewingCoder** [Lordmau5/FFS-v1.X#38]
So I'm here setting up bunch-o-tanks for a vid shoot.  showing off lots of materials.

rule #1 right -- wood burns.  So I make a tank out of oak planks and fill that bad boy with lava.  Surprisingly it doesn't burn to the ground.  Which makes what I wanted to shoot boring.

then....   the client crashes due to an unrelated mod issue (texture for thut).

on the reload of the world (playing SP) the tank _IS_ on fire.  I'm guessing in the short delay between world load and the multi-block load perhaps a plank caught fire.. who knows really.

anyway.. I'm joyously watching the tank starting to burn and feverishly trying to kick off the capture when it crashes.  

This time it's FFS.  Of course I mean; I _was_ filling a wooden framed FFS tank with lava.  So bad things are likely to happen.  

But I figured an FFS crash is an FFS crash and should be reported :)

Forge 11.15.1.1737
FFS 1.4.5.6.83

[crash-2016-02-10_14.12.05-client.txt.zip](https://github.com/Lordmau5/FFS/files/125368/crash-2016-02-10_14.12.05-client.txt.zip)

**Comment by Lordmau5** [comment]
I am pretty unsure as to where the issue might be caused.
I just committed a potential fix, would like to hear back if it fixes it.

Towards the burning:
It's actually still random.
The more fluid is in, the higher the chance (same with leaking) :P

**Comment by Lordmau5** [comment]
Any news on this with the latest alpha I've pushed out?

**Comment by Lordmau5** [comment]
Alright last chance.

If there's no response up until tomorrow evening, I'm gonna assume this is resolved and close it :)

**Comment by BrewingCoder** [comment]
close it!  I just reloaded that world and finally got it to actually burn rather than leak and it restarted twice in a row without hiccup so I'd consider my issue resolved.

Seems like it took much more effort this time to catch fire.. but leaked like a colander.

**Comment by Lordmau5** [comment]
Just a quick breakdown, since I saw the video you made ;)
- The chance of the tank catching fire is irrelevant of the amount of size of the tank, but of the relative amount of fluid inside it. If a 10x10x10 tank is filled with 50% lava, it'll have the same chance to catch fire as a 3x3x3 tank filled with 50% lava.
- The tanks don't _need_ a computer-interface. That one's optional. Only one valve is necessary - additional valves are also optional. This will also be the case with the upcoming Fluid-Energy Relay / Metaphaser "valve": In theory, you could build a tank with just that Relay.

**Comment by Drullkus** [comment]
Metaphaser is such a cool name 😊
