### ISSUE TITLE
1.9.0-Client crash when trying to break block on tank

### ISSUE THREAD

**Issue by RealGrep** [Lordmau5/FFS-v1.X#48]
**FancyFluidStorage Version**: 1.5.1.1.2

**MinecraftForge Version**: 1865

**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

http://pastebin.com/QggqxM4A

**What happens / happened?**:

Built tank with stone brick frame with glass, one valve and controller. Put syngas in it from Advanced Generators. Tried to break a block to put in second valve, leading to a crash. Breaking either the stone brick or glass make it crash.

**How can we reproduce it?**:

Build tank (say, 3x3), put computer and valve on, activate. Now try and break any block on it. Note that I have Chisel 2 installed (Chisel-MC1.9-0.0.4.13.jar). No blocks on it were chisel blocks, but from reading other old bug reports, it might be related.

**Comment by Lordmau5** [comment]
I'll have a look into it later today. 
I'm just about to go to work, so I can't look into it before 6pm GMT+1 :/

**Comment by RealGrep** [comment]
Darn work! XD No problem, thanks. :)

**Comment by Lordmau5** [comment]
I looked into it yesterday a bit and couldn't reproduce it, but I did start a bit of work on something different that could possibly prevent it from happening.

One other question I'd have would be:
_Did the crash happen when you **started** to break the block, or when the block **actually break** / you **finished** breaking the block?_

**Comment by RealGrep** [comment]
The instant the pickaxe hit the block, it crashed the client. The block didn't break and was there after I restarted.

**Comment by Lordmau5** [comment]
Ah, so you just **hit** the block and did not break it at that moment?

**Comment by RealGrep** [comment]
Yeah, I was trying to break it, but it crashed immediately when I tried. Was using the Botania Terra Shatterer (in normal one block break mode). I should try with a different pick and see what happens.

**Comment by RealGrep** [comment]
Sorry it took me a bit to test this, but I tried with just a vanilla iron pickaxe and it did the same thing. I then tried with just my hand. It seemed to show my hitting it a couple of times before it crashed the client, but crash it did. Hope that's of some use to you. More info can only help. Let me know if I can provide any other information.

**Comment by Lordmau5** [comment]
Good to know that this is not happening with just a specific pickaxe, but rather with everything. 

I barely had time to look into it the last few days, but I'll make sure to do so up until this weekend

**Comment by DingoX3** [comment]
Just wanted to confirm this is happening with Forge 1891 still. I found the only way to break it is in creative. It breaks the entire tank but leaves the one input valve(i only had the one), and if i rebuild the tank the fluid(lava) is still there. I assume the valve is the block that holds the memory of the fluid.

Full crash report here: http://pastebin.com/02d25gx1

**Comment by Lordmau5** [comment]
I've finally had some time to look at it and I think I know how to fix it.
I've added the "Help Wanted" label nontheless, if someone else comes up with a fix.

I know it's happening over here:
https://github.com/Lordmau5/FFS/blob/1.9/src/main/java/com/lordmau5/ffs/client/TankFrameModel.java#L57

The reason why:
Upon breaking the tank frame, the camo-block is `null` and therefore the Particle Texture is returning `null`.
**HOWEVER**:
The particle texture **must never** return `null`.

Another thing I'm going to tackle is to see what happens if I let the block break before calling the tile-method over here:
https://github.com/Lordmau5/FFS/blob/1.9/src/main/java/com/lordmau5/ffs/block/tanktiles/BlockTankFrame.java#L205
First calling the super method, then calling the TileEntity method (with caching it first).

**Comment by Lordmau5** [comment]
Need some feedback from you guys with v1.5.1.2.3

**Comment by Lordmau5** [comment]
Resolved?
