### ISSUE TITLE
StackOverflowError Server crash

### ISSUE THREAD

**Issue by mindcloud69** [Lordmau5/FFS-v1.X#54]
**FancyFluidStorage Version**: 1.7.10 1.3.7

**MinecraftForge Version**: 10.13.4.1614

**Client or Server?**:
- [ ] Client
- [X ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**: 
[ Server Crash Report](http://pastebin.com/SNJz9GKD)
[ Single Player Crash Report](http://pastebin.com/bkary60L)
the single player world is the server world dir copied over to the client saves dir.

**What happens / happened?**: Only happens with in a couple of minutes of creating a new tank. I will leave the area and come back and the server will crash. This happens on Single player and Server play. The area is chunk loaded. Tank size does not matter nor does the materials I am using. I have to remove the mod completely to get back in the world, I can't even mcedit the tank blocks out of the world. Server will start and as soon as I login it crashes. In the single player I can open the world and with in a couple of seconds of entering the game it crashes.

**How can we reproduce it?**: I can reproduce it nearly every time I create a new tank and leave and come back to the area.

**Comment by mindcloud69** [comment]
Wondering if it could have been the railcraft residual heat blocks? I was looking in mcedit and noticed they were inside the tank that caused the crash.

**Comment by Lordmau5** [comment]
Might be, I have no idea. 
You shouldn't use the residual heat anyway - they might mess with other mods, too. 

If disabling them fixes it, that's nice to hear :) 

If not, I'm sorry to say that I'm probably not going to fix any further bugs for 1.7.10, since we dropped support for that as soon as our first 1.9 build was released. 
It's just too much effort to keep 3 different versions up to date, sorry.
