### ISSUE TITLE
crash on startup with Fancy Fluid Storage-1.9.4

### ISSUE THREAD

**Issue by SDUBZ** [Lordmau5/FFS-v1.X#62]
**FancyFluidStorage Version**:
Fancy Fluid Storage-1.9.4-1.6.2-b21.jar
**MinecraftForge Version**:
Forge-1.9.4-12.17.0.1967.jar
**Client or Server?**:
- [x] Client
- [ ] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:http://pastebin.com/Rd6u3avG

**What happens / happened?**:
crashes on start up
**How can we reproduce it?**:
client log: 
[fml-client-latest (2).txt](https://github.com/Lordmau5/FFS/files/322075/fml-client-latest.2.txt)

**Comment by kolatra** [comment]
This is happening because there are some missing @Optional annotations and the mod has an accidental hard dependency on the Chisel API.

**Comment by Lordmau5** [comment]
**DON'T USE CHISEL 3 BECAUSE I'M NOT FUCKING SUPPORTING THIS BULLSHIT!**
`UC  chisel{3.0} [Chisel 3] (Chisel3-3.0.jar)`

Long story short:
Chisel 3 is not supported and the @Optional field is not kicking in properly.
Both mods, Chisel 3 and Chisel-Team's Chisel use the same modid, so the Optional field is useless.

I'm pushing a fix for this in a few minutes with a **FORCED** crash that tells the user to not use that version of Chisel.

CC: @TheCricket

//NinjaEdit:
@Kolatra, please forward this to your supervisor so he can change the modid of your mod.
Thank you.

**Comment by Lordmau5** [comment]
Ask and ye shall receive.

![Image](https://i.lordmau5.com/1466334337-1196.png)

**Comment by TheCricket** [comment]
I'm not his supervisor :P Glad to see you're pulling a mDiyo-Gregtech move out of this :)

**Comment by TheCricket** [comment]
Honestly though. I'm not crashing your mod. There isn't a single line of code in there to do it. You are crashing your own mod :)

**Comment by Lordmau5** [comment]
Well, you're one special moron, aren't you?
Point of attention, even trying to get a "notice me senpai" from Pahimar, isn't that cute?

I'm still waiting for the day you're changing the modid over to `chisel-3` or `chisel-cricket-edition-with-a-lot-of-shitstorm-boiling-up` :)

//EDIT:
_Glad to see you're pulling a mDiyo-Gregtech move out of this :)_

Except that I'm not because this is a different situation.
I doubt Tinkers' Construct and GregTech had the same modid at a certain point in time, did they?
