### ISSUE TITLE
Crash w/ Extra Utils 2

### ISSUE THREAD

**Issue by WenXin20** [Lordmau5/FFS-v1.X#74]
**FancyFluidStorage Version**: 1.10.2-1.6.4-b28

**MinecraftForge Version**: 1.10.2-2062

**Client or Server?**:
- [x] Client

**Crash Report**:
http://pastebin.com/NtPeb9V6

**What happens / happened?**:
Crash when a pipe from [Extra Utils 2](https://minecraft.curseforge.com/projects/extra-utilities) was placed next to a tank.

**How can we reproduce it?**:
Just place a pipe next to a tank, which crashed my game.

**Comment by Lordmau5** [comment]
I wouldn't mind "dragging" @rwtema in here, since this is kinda caused on his end by trying to cast a class / state of one of the blocks in my mod to a state in his mod.
I'd like to check into his method call in the specific class (`com.rwtema.extrautils2.backend.model.PassthruModelBlock.func_188616_a(PassthruModelBlock.java:37)`), but since his mod isn't open source, things get a little bit tricky here..

If I am doing anything wrong here and Tema might know what it is, it'd be awesome if he could enlighten me on it so I can fix it :)

**Comment by Lordmau5** [comment]
Poking @rwtema once again but I doubt he'll actually react this time around.
